name: Deploy on Release
on:
  release:
    types:
      - created

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Set up JDK and Maven Central Repository
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 8
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          server-id: central
          server-username: CENTRAL_PUBLISHING_USERNAME
          server-password: CENTRAL_PUBLISHING_TOKEN
      - name: Deploy
        run: mvn clean deploy --batch-mode --show-version
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CENTRAL_PUBLISHING_USERNAME: ${{ secrets.CENTRAL_PUBLISHING_USERNAME }}
          CENTRAL_PUBLISHING_TOKEN: ${{ secrets.CENTRAL_PUBLISHING_TOKEN }}